[package]
name = "vm_effector"
version = "0.1.3"
edition = "2018"

[[bin]]
name = "vm_effector"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.14.0"

[dev-dependencies]
marine-rs-sdk-test = "0.16.1"
